### ISSUE TITLE
Remove torrent after reaching a given ratio

### ISSUE THREAD

**Issue by Spamme1** [hadouken/hadouken#227]
Some other bittorrent clients have an option to automatically remove a torrent after reaching a given upload/download ratio. I always found this option really useful, I could always seed the torrent until reaching 3 or 4 ratio and then automatically remove them.

**Comment by vktr** [comment]
See http://docs.hdkn.net/en/latest/configuration.html#seed-goals

The functionality is currently broken, but was fixed in #221 which will be released in the next version.

**Comment by syrys** [comment]
@vktr Im assuming this is not yet fixed, do you have an ETA for this at all? Loving the app, but its quickly filling up with completed torrents and i have to manually go in and remove them.

Also, does does the following work as i think it does? (regardless of seed-ratio/seed-time, the torrent will be removed from the client immediately upon completion?)

```
  "defaultOptions":{
      "seedRatio": 0,
      "seedTime": 0,
      "seedAction": "remove"
    }
```

**Comment by vktr** [comment]
Hi @syrys! Sorry for the late answer. I haven't worked on Hadouken for quite a while, and can't give any ETA on when the next release will be. I'll try to make something happen, though :smile:

**Comment by syrys** [comment]
@vktr thanks for the response. This is an amazing torrent client, but has a lot of bugs thats making it unusable for me. Rather than making new threads for all of them, ill just list them here so you are aware of them.
- client is limited to 5 active downloads and no documented way to increase the limit.
- seedRatio/time feature is broken. Its simply incorrect behaviour, heck even the variable name is wrong at one point haha. Also, 0 for either of these would get ignored as well, even if the rest of the code gets fixed.
- All finished downloads restart from scratch upon OS restart.

hope that helps for future :D

**Comment by syrys** [comment]
@vktr 
`https://github.com/hadouken/hadouken/blob/develop/js/core.js#L149`
this should be seedTime not goalTime. also, the seedTime and seedRatio coming from options is always undefined here. hope that helps.

**Comment by Robo210** [comment]
> All finished downloads restart from scratch upon OS restart.

Are you able to provide more details about this? Do you have to download the entire file over again, or are you referring to the file being re-hashed (which may still show a progress bar starting at 0%)? I've never see Hadouken have to re-download files because it or the OS restarted, or even because the service died unexpectedly. If this is something that happens to you every time, any more details you can provide would be very helpful to getting the issue fixed.

**Comment by syrys** [comment]
@Robo210 Hey there. Unfortunately i uninstalled it for the time being, if i get around to trying it out, i will get back to you with more details.

But to give you a rough idea, i used this with Sonarr. Downloads mostly worked well, but when a restart happened, i would see downloads starting up again from scratch. It did say downloading. If the rehashing process also says downloading, well i cant really give you any useful info there. The download happened pretty fast, but then again i have a 200/200 internet connection, so downloads happen pretty fast to begin with. Also this might be helpful, but I cannot confirm if the file was deleted prior to the OS restart (cant remember if sonarr successfully managed to automatically delete the file from hadouken or not). Either way though, hadouken should not start a download that was previously stopped or previously completed even if the file is missing, rather it should display the file as a state of error if anything.

That being said, since sonarr supports hadouken, probably try give them both a go and see how well they work together, you will likely get a whole bunch of users from sonarr (me included) if integration works well.

**Comment by syrys** [comment]
@Robo210 i see your commit. just to point out:

```
        var goalRatio = options.seedRatio || 2.0;
        var goalTime  = options.seedTime || 0;
```

in your code, `options.seedTime || 0;` is redundant, as you always set options.seedTime. This also opens up to `options.seedRatio` and `options.seedTime` not being allowed to be 0 (javascript). You should be checking if the variables are defined (not undefined) and not null (something like [this](http://stackoverflow.com/a/6509422/3867072)). This is also the case where you originally pulls these data from the json file (you should allow 0, as its a valid value, but maybe check if its a valid number and if its `>= 0`).

That being said, if you can somehow output the `options.seedRatio` and `options.seedTime`, you will notice that these are always undefined (guessing they dont get set properly to begin with).

sorry @vktr, i didnt mean to tag you here, i read the commit wrong.
